// Generated by CoffeeScript 1.6.3
(function() {
  window.oPage = oFinalPage.extend({
    fRefresh: function(bRefresh) {
      return this._super();
    },
    fBind: function() {},
    __fInitData: function() {}
  });

}).call(this);
