var oTemplate=new Hogan.Template();oTemplate.r =function(c,p,i){var _=this;_.b(i=i||"");_.b("<div>");_.b("\n" + i);_.b("    欢迎来到后台管理。");_.b("\n" + i);_.b("</div>");return _.fl();;};
// Generated by CoffeeScript 1.6.3
(function() {
  window.oPage = oFinalPage.extend({
    fRefresh: function(bRefresh) {
      return this._super();
    },
    fBind: function() {},
    __fInitData: function() {}
  });

}).call(this);
