// Generated by CoffeeScript 1.6.3
(function() {
  window.oFinalPage = Class.extend({
    init: function(oArgs) {
      this.oArgs = oArgs;
      return this.__fInitData();
    },
    __fInitData: function() {},
    fPrint: function() {
      document.write('<div class="maincontent"></div>');
      return this.fRefresh();
    },
    fRefresh: function(bRefresh) {
      bRefresh = bRefresh != null ? bRefresh : false;
      $('.maincontent').html(this.oArgs.oTemplate.render(this.oArgs.oParams, this.oArgs.oPartials));
      return this.fBind();
    },
    fBind: function() {
      return $('.js_back').click(function() {
        return State.back(1);
      });
    }
  });

}).call(this);

var footerTemplate=new Hogan.Template();footerTemplate.r =function(c,p,i){var _=this;_.b(i=i||"");_.b("<div class=\"header\"></div>");return _.fl();;};
var headerTemplate=new Hogan.Template();headerTemplate.r =function(c,p,i){var _=this;_.b(i=i||"");_.b("<div class=\"footer\"></div>");return _.fl();;};