var oTemplate=new Hogan.Template();oTemplate.r =function(c,p,i){var _=this;_.b(i=i||"");_.b("<div>首页</div>");_.b("\n" + i);_.b("<div><a class=\"js_back\">返回</a></div>");_.b("\n" + i);_.b("<div>test:");_.b(_.v(_.f("test",c,p,0)));_.b("</div>");_.b("\n" + i);_.b(_.rp("testTest",c,p,""));return _.fl();;};
// Generated by CoffeeScript 1.6.3
(function() {
  window.oPage = oFinalPage.extend({
    fRefresh: function(bRefresh) {
      return this._super();
    },
    fBind: function() {},
    __fInitData: function() {}
  });

}).call(this);
