var oTemplate=new Hogan.Template();oTemplate.r =function(c,p,i){var _=this;_.b(i=i||"");_.b("<div class=\"\">");_.b("\n" + i);_.b("    <div class=\"m10 wall js_btns\">");_.b("\n" + i);_.b("        <button class=\"js_push\">发布</button>");_.b("\n" + i);_.b("    </div>");_.b("\n" + i);_.b(_.rp("blogEditTpl",c,p,"    "));_.b("    ");_.b("\n" + i);_.b("</div>");return _.fl();;};
// Generated by CoffeeScript 1.6.3
(function() {
  window.oPage = oFinalPage.extend({
    fRefresh: function(bRefresh) {
      return this._super();
    },
    fBind: function() {
      var me, oContent;
      me = this;
      oContent = UE.getEditor('blog_content');
      oContent.ready(function() {
        return this.setContent(me.oArgs.oParams.blog.content);
      });
      return $('.js_push').click(function() {
        var oFormData;
        oFormData = new FormData(document.getElementById("js_form_blog"));
        oFormData.append('id', me.oArgs.oParams.blog.blogId);
        oFormData.append('content', oContent.getContent());
        fOneAjax('Blog', 'AjaxEdit', oFormData, function(o) {
          if (o.code === 1) {
            return State.back(0);
          } else {
            return fShowErrors(o.erros);
          }
        }, this, true);
        return false;
      });
    },
    __fInitData: function() {
      var params;
      params = this.oArgs.oParams;
      return $.each(params.blogCategoryList, function(k, v) {
        if (v.blogCategoryId === params.blog.blogCategoryId) {
          return v.selected = true;
        }
      });
    }
  });

}).call(this);
