var oTemplate=new Hogan.Template();oTemplate.r =function(c,p,i){var _=this;_.b(i=i||"");_.b("<div class=\"\">");_.b("\n" + i);_.b("    <div>");_.b("\n" + i);_.b("        <form id=\"blogCategoryForm\">");_.b("\n" + i);_.b("            <span><input type=\"text\" name=\"name\" placeholder=\"分类名\"/></span>");_.b("\n" + i);_.b("            <span><input type=\"submit\" value=\"添加\"/></span>");_.b("\n" + i);_.b("        </form>");_.b("\n" + i);_.b("    </div>");_.b("\n" + i);_.b("    <ul id=\"blogCategoryList\">");_.b("\n" + i);if(_.s(_.f("aList",c,p,1),c,p,0,269,857,"{{ }}")){_.rs(c,p,function(c,p,_){_.b("        <li class=\"clearfix js_draggable\" id=\"js_blogCategoryId_");_.b(_.v(_.f("blogCategoryId",c,p,0)));_.b("\">");_.b("\n" + i);_.b("            <span class=\"fl mr10\"><a id=\"js_blogCategoryName_");_.b(_.v(_.f("blogCategoryId",c,p,0)));_.b("\">");_.b(_.v(_.f("name",c,p,0)));_.b("</a></span>");_.b("\n" + i);_.b("            <span class=\"fl\"><a id=\"js_blogIndex_");_.b(_.v(_.f("blogCategoryId",c,p,0)));_.b("\">博客数:");_.b(_.v(_.f("blogCount",c,p,0)));_.b("</a></span>");_.b("\n" + i);if(_.s(_.f("deleteFlag",c,p,1),c,p,0,581,682,"{{ }}")){_.rs(c,p,function(c,p,_){_.b("            <span class=\"fr mr10\"><a id=\"js_recover_");_.b(_.v(_.f("blogCategoryId",c,p,0)));_.b("\">取消删除</a></span>");_.b("\n");});c.pop();}if(!_.s(_.f("deleteFlag",c,p,1),c,p,1,0,0,"")){_.b("            <span class=\"fr mr10\"><a id=\"js_delete_");_.b(_.v(_.f("blogCategoryId",c,p,0)));_.b("\">删除</a></span>");_.b("\n");};_.b("        </li>");_.b("\n");});c.pop();}_.b("    </ul>");_.b("\n" + i);_.b("</div>");return _.fl();;};
// Generated by CoffeeScript 1.6.3
(function() {
  window.oPage = oFinalPage.extend({
    fRefresh: function(bRefresh) {
      this._super();
      return this.__sortAble();
    },
    fBind: function() {
      $('[id^=js_blogCategoryName_]').click(function() {
        return false;
      });
      $('[id^=js_blogIndex_]').click(function() {
        var id;
        id = this.id.replace('js_blogIndex_', '');
        State.forward('Blog', 'Index', {
          blogCategoryId: id
        });
        return false;
      });
      $('[id^=js_delete_]').click(function() {
        var id;
        id = this.id.replace('js_delete_', '');
        fOneAjax('blogCategory', 'AjaxDelete', {
          id: id
        }, function(o) {
          if (o.code === 1) {
            return State.back(0);
          }
        }, this);
        return false;
      });
      $('[id^=js_recover_]').click(function() {
        var id;
        id = this.id.replace('js_recover_', '');
        fOneAjax('blogCategory', 'AjaxRecover', {
          id: id
        }, function(o) {
          if (o.code === 1) {
            return State.back(0);
          }
        }, this);
        return false;
      });
      $('#blogCategoryForm').submit(function() {
        var data;
        data = $(this).serialize();
        fOneAjax('blogCategory', 'AjaxAdd', data, function(o) {
          if (o.code === 1) {
            return State.back(0);
          }
        }, this);
        return false;
      });
      return this;
    },
    __fInitData: function() {},
    __sortAble: function() {
      var fSubmit, fUpdate, list, originOrder;
      list = $("#blogCategoryList");
      originOrder = [];
      list.children("li").each(function() {
        originOrder.push(this.id.replace('js_blogCategoryId_', ''));
        return $(this).attr("title", "你可以拖动进行排序");
      });
      originOrder = originOrder.join(',');
      fUpdate = function(ids, itemorder) {
        originOrder = ids;
        return fOneAjax('BlogCategory', 'AjaxSort', {
          ids: ids
        }, function(o) {
          if (o.code === 1) {
            return console.log('ok');
          }
        }, $('#blogCategoryList'));
      };
      fSubmit = function() {
        var order;
        order = [];
        list.children("li").each(function() {
          return order.push(this.id.replace('js_blogCategoryId_', ''));
        });
        return fUpdate(order.join(','));
      };
      return list.sortable({
        opacity: 0.7,
        update: function() {
          return fSubmit();
        }
      });
    }
  });

}).call(this);
