var oTemplate=new Hogan.Template();oTemplate.r =function(c,p,i){var _=this;_.b(i=i||"");_.b("<div class=\"\">");_.b("\n" + i);_.b("    <p class=\"mb1\">博客列表</p>");_.b("\n" + i);_.b("    <ul>");_.b("\n" + i);if(_.s(_.f("aList",c,p,1),c,p,0,66,285,"{{ }}")){_.rs(c,p,function(c,p,_){_.b("        <li class=\"clearfix\">");_.b("\n" + i);_.b("            <a id=\"js_blog_");_.b(_.v(_.f("blogId",c,p,0)));_.b("\">");_.b("\n" + i);_.b("                <span class=\"fl\">");_.b(_.v(_.f("title",c,p,0)));_.b("</span>");_.b("\n" + i);_.b("            </a>");_.b("\n" + i);_.b("            <span class=\"fr\">");_.b(_.v(_.d("sceneParams.createTime",c,p,0)));_.b("</span>");_.b("\n" + i);_.b("        </li>");_.b("\n");});c.pop();}_.b("    </ul>");_.b("\n" + i);_.b("</div>");return _.fl();;};
// Generated by CoffeeScript 1.6.3
(function() {
  window.oPage = oFinalPage.extend({
    fRefresh: function(bRefresh) {
      return this._super();
    },
    fBind: function() {
      return $('[id^=js_blog_]').click(function() {
        var id;
        id = this.id.replace('js_blog_', '');
        State.forward('Blog', 'Blog', {
          id: id
        });
        return false;
      });
    },
    __fInitData: function() {}
  });

}).call(this);
